# Site settings
title: Malscan
email: josh@joshgrancell.com
description: > # this means to ignore newlines until "baseurl:"
  Malscan is a light weight, powerful linux malware scanner designed
  for desktop, webservers, and linux infrastrucutre. Malscan is open
  source and free software licensed under the MIT License.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.malscan.org" # the base hostname & protocol for your site
github_username:  jgrancell

# Build settings
markdown: kramdown
highlighter: pygments

## Global settings
malscan-version: 1.7.0
malscan-release-date: "April 24, 2016"
